name: my_portfolio
description: "This Project is for my Personal Portfolio"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  firebase_core: ^3.13.0
  firebase_database: ^11.3.5
  flutter_animate: ^4.5.2
  shared_preferences: ^2.5.3
  go_router: ^15.1.1
  flutter_bloc: ^9.1.0
  dartx: ^1.2.0
  google_fonts: ^6.2.1
  fluentui_system_icons: ^1.1.273
  gap: ^3.0.1
  simple_icons: ^14.6.1
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/img/

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/IMG_20240628_162010_317 (1)~2 (1).jpg"
    background_color: "#4CAF50"
    theme_color: "#4CAF50"
